name: Deploy to Homelab

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Local Docker Containers
        run: |
          # Pull the latest changes
          git pull origin master
          
          # Rebuild and restart the Docker containers
          docker-compose up -d --build
