name: Deploy to Homelab

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Homelab via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to the repository folder on the server
            cd /opt/calyx
            
            # Pull the latest changes from the repository
            git pull origin master
            
            # Rebuild and restart the Docker containers in the background
            docker-compose up -d --build
